services:
  lsyncd-rsync:
    image: zhh1115/lsyncd:latest
    restart: unless-stopped
    command: -delay 0 -rsync /source /dest
    volumes:
      - /root:/source
      - /tmp:/dest

  lsyncd-rsyncssh:
    image: zhh1115/lsyncd:latest
    restart: unless-stopped
    command: -delay 0 -rsyncssh /source 10.0.100.3 /tmp
    volumes:
      - /root/.ssh:/root/.ssh
      - /root:/source
