version: "3.7"

services:
  keepalived:
    image: zhh1115/keepalived:2.0.20
    container_name: keepalived
    cap_add:
      - NET_ADMIN
    privileged: true
    network_mode: "host"
    volumes:
     - /etc/keepalived/keepalived.conf:/usr/local/keepalived/etc/keepalived.conf
    restart: unless-stopped
